initial profile support

diff --git a/lightum-indicator b/lightum-indicator
--- a/lightum-indicator
+++ b/lightum-indicator
@@ -23,6 +23,26 @@ if [ ! -e "${HOME}/.config/autostart/lightum-indicator.desktop" ]; then
 	cp /usr/share/applications/lightum-indicator.desktop ${HOME}/.config/autostart/lightum-indicator.desktop
 fi
 
+profiles=`grep "^#PROFILE: " ${CONFDIR}/* |cut -f 1 -d ":" |grep -v "${CONFIG}" |sort -u`
+
+currentprofile=`grep "^#PROFILE: " ${CONFIG} |cut -f 2 -d " "`
+if [ -z "${currentprofile}" ]; then currentprofile="Default" ; fi
+
+PROFILEOPTS="Profile:$currentprofile:Save As..."
+
+for file in ${profiles} ; do
+	profile=`cat ${file} |grep "^#PROFILE: " |cut -f 2 -d " "`
+	if [ "${profile}" == "${currentprofile}" ]; then
+		PROFILEOPTS="${PROFILEOPTS}
+Profile:$profile:*Load
+Profile:$profile:*Delete"
+	else
+		PROFILEOPTS="${PROFILEOPTS}
+Profile:$profile:Load
+Profile:$profile:Delete"
+	fi
+done
+
 manualmode=`cat ${CONFIG} |grep "^manualmode="`
 case "$manualmode" in
 "manualmode=1")
@@ -84,6 +104,7 @@ ICON="/usr/share/lightum-indicator/icons/${IC1}${IC2}.png"
 
 echo "$MANUALMODEOPTS
 $WORKMODEOPTS
+$PROFILEOPTS
 About" | \
 /usr/share/lightum-indicator/cappind-lightum.py -p -i ${ICON} | \
 while read s; do
@@ -170,7 +191,7 @@ case "$s" in
 ;;
 "Keyboard Options:Max Brightness")
 	cv=`cat ${CONFIG} |grep "^maxbrightness=" |cut -f 2 -d "="`
-	if [ -z $cv ]; then cv=255 ; fi
+	if [ -z "$cv" ]; then cv=255 ; fi
 	ans=`${ZEN} --forms --add-entry="maximum keyboard brightness value (between 4 and 255)" --text="current value: $cv"`
 	if [ $? == 0 ]; then 
 		if [ ${ans} -le 255 ] && [ ${ans} -ge 4 ]; then
@@ -189,7 +210,7 @@ case "$s" in
 ;;
 "Keyboard Options:Min Brightness")
 	cv=`cat ${CONFIG} |grep "^minbrightness=" |cut -f 2 -d "="`
-	if [ -z $cv ]; then cv=0 ; fi
+	if [ -z "$cv" ]; then cv=0 ; fi
 	ans=`${ZEN} --forms --add-entry="minimum keyboard brightness value (between 0 and 3)" --text="current value: $cv"`
 	if [ $? == 0 ]; then 
 		if [ ${ans} -le 3 ] && [ ${ans} -ge 0 ]; then
@@ -208,7 +229,7 @@ case "$s" in
 ;;
 "Keyboard Options:Dim on idle time")
 	cv=`cat ${CONFIG} |grep "^idleoff=" |cut -f 2 -d "="`
-	if [ -z $cv ]; then cv=5 ; fi
+	if [ -z "$cv" ]; then cv=5 ; fi
 	ans=`${ZEN} --forms --add-entry="Dim keyboard brightness if computer unused for X seconds" --text="current value: $cv"`
 	if [ $? == 0 ]; then 
 		if [ ${ans} -le 86400 ] && [ ${ans} -ge 0 ]; then
@@ -227,7 +248,7 @@ case "$s" in
 ;;
 "Screen Options:Max Backlight")
 	cv=`cat ${CONFIG} |grep "^maxbacklight=" |cut -f 2 -d "="`
-	if [ -z $cv ]; then cv=15 ; fi
+	if [ -z "$cv" ]; then cv=15 ; fi
 	ans=`${ZEN} --forms --add-entry="maximum screen backlight value (between 4 and 15)" --text="current value: $cv"`
 	if [ $? == 0 ]; then 
 		if [ ${ans} -le 15 ] && [ ${ans} -ge 4 ]; then
@@ -246,7 +267,7 @@ case "$s" in
 ;;
 "Screen Options:Min Backlight")
 	cv=`cat ${CONFIG} |grep "^minbacklight=" |cut -f 2 -d "="`
-	if [ -z $cv ]; then cv=0 ; fi
+	if [ -z "$cv" ]; then cv=0 ; fi
 	ans=`${ZEN} --forms --add-entry="minimum screen backlight value (between 0 and 3)" --text="current value: $cv"`
 	if [ $? == 0 ]; then 
 		if [ ${ans} -le 3 ] && [ ${ans} -ge 0 ]; then
@@ -265,7 +286,7 @@ case "$s" in
 ;;
 "Screen Options:Dim on idle time")
 	cv=`cat ${CONFIG} |grep "^screenidle=" |cut -f 2 -d "="`
-	if [ -z $cv ]; then cv=30 ; fi
+	if [ -z "$cv" ]; then cv=30 ; fi
 	ans=`${ZEN} --forms --add-entry="Dim screen backlight if computer unused for X seconds" --text="current value: $cv"`
 	if [ $? == 0 ]; then 
 		if [ ${ans} -le 86400 ] && [ ${ans} -ge 0 ]; then
@@ -285,5 +306,81 @@ case "$s" in
 "About")
 	${ZEN} --no-wrap --info --text "lightum-indicator version ${VERSION}\n(c)2012 Pau Oliva Fora\nLicensed under GPL"
 ;;
+
+
+
+*)
+	# handle profiles here
+	echo "$s" |grep "Profile:.*:Save As..." >/dev/null
+	if [ $? == 0 ]; then
+		ans=`${ZEN} --forms --add-entry="Profile name (max 8 chars, no spaces)" --text="Enter the new profile name"`
+		profile=$(echo `echo "${ans}" |grep -oi "[a-z]"` |sed -e "s/ //g" |cut -c "1-8")
+		write="yes"
+		if [ -z "${profile}" ]; then
+			${ZEN} --no-wrap --error --text "Invalid profile name."
+		else 
+
+			if [ -f "${CONFDIR}/lightum-${profile}.conf" ]; then
+				write="no"
+				${ZEN} --no-wrap --question --text="a profile named '${profile}' already exists. Overwrite?"
+				if [ $? == 0 ]; then
+					write="yes"
+				fi
+			fi
+
+			if [ "${write}" == "yes" ]; then
+				grep "^#PROFILE: " ${CONFIG}
+				if [ $? == 0 ]; then
+					sed -i "s/^#PROFILE: .*/#PROFILE: ${profile}/" ${CONFIG}
+				else
+					echo "#PROFILE: ${profile}" >> ${CONFIG}
+				fi
+				cp "${CONFIG}" "${CONFDIR}/lightum-${profile}.conf"
+				${ZEN} --no-wrap --info --text "Profile '${profile}' successfully saved."
+				killall lightum 2>/dev/null
+				/usr/bin/lightum
+				lightumreload
+				${CONFDIR}/lightum-reload.$$ &
+			fi
+		fi
+	fi
+
+	echo "$s" |grep "Profile:.*:Load" >/dev/null
+	if [ $? == 0 ]; then
+		profile=`echo $s |cut -f 2 -d ":"`
+		if [ -f "${CONFDIR}/lightum-${profile}.conf" ]; then
+			${ZEN} --no-wrap --question --text="Load profile '${profile}'?"
+			if [ $? == 0 ]; then
+				cp "${CONFDIR}/lightum-${profile}.conf" "${CONFIG}"
+				killall lightum 2>/dev/null
+				/usr/bin/lightum
+				lightumreload
+				${CONFDIR}/lightum-reload.$$ &
+			fi
+		else
+			${ZEN} --no-wrap --error --text "Could not load profile, sorry."
+		fi
+	fi
+
+	echo "$s" |grep "Profile:.*:Delete" >/dev/null
+	if [ $? == 0 ]; then
+		profile=`echo $s |cut -f 2 -d ":"`
+		if [ -f "${CONFDIR}/lightum-${profile}.conf" ]; then
+			${ZEN} --no-wrap --question --text="Really delete profile '${profile}'?"
+			if [ $? == 0 ]; then
+				rm -f "${CONFDIR}/lightum-${profile}.conf"
+				killall lightum 2>/dev/null
+				/usr/bin/lightum
+				lightumreload
+				${CONFDIR}/lightum-reload.$$ &
+			fi
+		else
+			${ZEN} --no-wrap --error --text "Could not delete profile, sorry."
+		fi
+	fi
+
+;;
+
+
 esac
 done
